package: community.lazycat.app.lightbws
version: 0.2.5
name: LightBWS
description: "A self-hosted, SDK-compatible Bitwarden Secrets Manager server"
author: ca-x
license: LicenseRef-LightBWS
homepage: https://github.com/ca-x/lightbws
min_os_version: 1.5.0
permissions:
  required:
    - net.internet
locales:
  zh:
    name: LightBWS
    description: "自托管、兼容 Bitwarden SDK 的密钥管理服务"
  en:
    name: LightBWS
    description: "A self-hosted, SDK-compatible Bitwarden Secrets Manager server"
